# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=300000)),
                ('due_date', models.DateField(verbose_name='charge due date')),
                ('is_payed', models.BooleanField(default=False)),
                ('_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('postal_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=300000)),
                ('due_date', models.DateField(verbose_name='charge due date')),
                ('is_payed', models.BooleanField(default=False)),
                ('_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payement_date', models.DateField(verbose_name='date for payement')),
                ('payement', models.IntegerField(default=1000000)),
                ('backup_payement', models.IntegerField(default=4000000)),
                ('_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='notification date')),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=300)),
                ('_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('_building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Building')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='date of payment')),
                ('amount', models.IntegerField(default=2000000)),
                ('is_payed', models.BooleanField(default=False)),
                ('delay_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('national_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('neighbor_name', models.CharField(max_length=100)),
                ('neighbor_family_name', models.CharField(max_length=100)),
                ('username', models.CharField(default='Untitiled', max_length=30)),
                ('password', models.CharField(default='123456', max_length=30)),
                ('sex', models.CharField(max_length=5, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('bank_account', models.CharField(max_length=30)),
                ('_apartment', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Apartment')),
                ('_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('national_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='RequestLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('type', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=300)),
                ('receiver', models.ManyToManyField(to='polls.Neighbor')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_RequestLetter_related', related_query_name='polls_RequestLetters', to='polls.Neighbor')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=1)),
                ('date_time', models.DateTimeField(verbose_name='date of reservation')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Facility')),
                ('neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Neighbor')),
            ],
        ),
        migrations.CreateModel(
            name='UnAvailableTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='available times')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='WarningLetter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('text', models.CharField(max_length=300)),
                ('receiving_neighbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Neighbor')),
            ],
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Owner'),
        ),
        migrations.AddField(
            model_name='monthlypayment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Neighbor'),
        ),
        migrations.AddField(
            model_name='contract',
            name='_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Owner'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Neighbor'),
        ),
        migrations.AddField(
            model_name='charge',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Receipt'),
        ),
        migrations.AddField(
            model_name='bill',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Receipt'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Owner'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Building'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='main_neighbor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Neighbor'),
        ),
        migrations.AlterUniqueTogether(
            name='warningletter',
            unique_together=set([('receiving_neighbor', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set([('neighbor', 'facility', 'date_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together=set([('receipt_number', '_bank')]),
        ),
        migrations.AlterUniqueTogether(
            name='monthlypayment',
            unique_together=set([('due_date', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together=set([('name', '_building')]),
        ),
        migrations.AlterUniqueTogether(
            name='dashboard',
            unique_together=set([('_building', 'date_time')]),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set([('_owner', 'tenant', '_apartment')]),
        ),
        migrations.AlterUniqueTogether(
            name='charge',
            unique_together=set([('due_date', '_apartment')]),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set([('due_date', '_apartment')]),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together=set([('building', 'floor')]),
        ),
    ]
