# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_apartment__owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='title',
        ),
    ]
