# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170812_1923'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set([('neighbor', 'facility')]),
        ),
    ]
