# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170812_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='duration',
        ),
        migrations.AddField(
            model_name='reservation',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_partition',
            field=models.IntegerField(default=1),
        ),
    ]
