# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-12 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170812_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='main_neighbor',
        ),
        migrations.AddField(
            model_name='neighbor',
            name='apartment',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Apartment'),
        ),
    ]
