# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170813_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='_bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Bank'),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='bank_account',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
