# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20170813_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='national_id',
            field=models.CharField(default='1111', max_length=10, primary_key=True, serialize=False),
        ),
    ]
