# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0012_auto_20170813_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighor1',
            fields=[
                ('national_id', models.CharField(default='1111', max_length=10, primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=5, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('bank_account', models.CharField(max_length=30, null=True)),
                ('_bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Bank')),
                ('apartment', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Apartment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
