# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 05:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0014_auto_20170816_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighor1',
            name='_bank',
        ),
        migrations.RemoveField(
            model_name='neighor1',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='neighor1',
            name='user',
        ),
        migrations.RemoveField(
            model_name='neighbor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='neighbor',
            name='neighbor_family_name',
        ),
        migrations.RemoveField(
            model_name='neighbor',
            name='neighbor_name',
        ),
        migrations.RemoveField(
            model_name='neighbor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='neighbor',
            name='username',
        ),
        migrations.AddField(
            model_name='neighbor',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.DeleteModel(
            name='Neighor1',
        ),
    ]
